AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*

Style/StringLiterals:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 10

Style/Documentation: 
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false