# frozen_string_literal: true

json.id professional_development_content.id
json.journalEntryId professional_development_content.journal_entry.id
json.title professional_development_content.title
json.mood professional_development_content.mood
json.todayILearned professional_development_content.today_i_learned
json.goalProgress professional_development_content.goal_progress
json.celebrations professional_development_content.celebrations
json.createdAt professional_development_content.created_at
json.updatedAt professional_development_content.updated_at
json.url professional_development_content_url(professional_development_content, format: :json)
